Handle input prompts with Click
aramis-lab/clinica pull request #301
Opened 2021-06-26 22:42 UTC by ghisvail

2021-06-28 07:48 UTC, omar-rifai requested changes
Thanks. This seems OK but why are you only handling this specific case? Other cases such as the interactive prompt in check_volume_location_in_world_coordinate_system seem to be require the same modification.

2021-06-28 08:06 UTC, ghisvail commented on clinica/iotools/utils/data_handling.py
> +        cmd_line = f"`clinica iotools center-nifti {abspath(bids_dir)} {abspath(bids_dir)}_centered --modality {modality}`"
Black reformatting

2021-06-28 08:06 UTC, ghisvail commented on clinica/iotools/utils/data_handling.py
> +            )
Black reformatting

2021-06-28 08:09 UTC, ghisvail commented
> Thanks. This seems OK but why are you only handling this specific case? Other cases such as the interactive prompt in check_volume_location_in_world_coordinate_system seem to be require the same modification.

Done.

2021-06-28 08:58 UTC, omar-rifai commented
There are at least two additional cases in engine.py but I may have missed others.

2021-06-28 09:00 UTC, ghisvail commented
They are hard to find. If you know where they are, please give me a list 👍

2021-06-28 09:21 UTC, omar-rifai commented
I agree. I just ran a search with the term "input()" and "stdin" and the only two remaining seem to be in nifd_to_bids.py. That should cover all the cases.

2021-06-30 10:33 UTC, ghisvail commented on clinica/pipelines/engine.py
> +                f"Number of threads set to {n_procs}. You may set the --n_procs argument "
There is no such feature in Click. We are either interactive or we are not.

2021-06-30 10:36 UTC, ghisvail commented on clinica/pipelines/engine.py
> +                f"Number of threads set to {n_procs}. You may set the --n_procs argument "
Relying on interactivity + timeouts for cluster usage is very bad practice and should not be encouraged.

2021-06-30 10:38 UTC, omar-rifai commented on clinica/pipelines/engine.py
> +                f"Number of threads set to {n_procs}. You may set the --n_procs argument "
Perhaps this issue is no longer relevant after [PR210](https://github.com/aramis-lab/clinica/pull/210), can you confirm it was correctly integrated with click as well?

2021-06-30 10:48 UTC, ghisvail commented on clinica/pipelines/engine.py
> +                f"Number of threads set to {n_procs}. You may set the --n_procs argument "
We have got support for the `yes` flag, which should propagate to the `skip_question` parameter.

That being said, a better UX design would be a `--interactive/--no-interactive` flag which explicitly signals whether the user want to run the pipeline with or without prompts. `n_procs` can be set to an arbitrary value with or without interactivity and `yes` is a poor choice to express that in my opinion.

2021-06-30 11:29 UTC, omar-rifai commented on clinica/pipelines/engine.py
> +                f"Number of threads set to {n_procs}. You may set the --n_procs argument "
Ok ! Can you please add this as enhancement issue? I'll merge this PR in the meantime.

2021-06-30 11:33 UTC, omar-rifai approved these changes

2021-06-30 11:33 UTC, merged

2021-06-30 12:04 UTC, ghisvail commented on clinica/pipelines/engine.py
> +                f"Number of threads set to {n_procs}. You may set the --n_procs argument "
See https://github.com/aramis-lab/clinica/issues/306