Fix image path finder in ADNI converter
aramis-lab/clinica pull request #411
Opened 2021-09-06 16:44 UTC by ghisvail

ADNI (like NIFD actually) seem to have slightly tweaked the file organization of the source data, which broke the image path finder for newer downloads (hello participant `002_S_1261`). LONI converters should no longer rely on parsing directory layouts and instead parse the image data filenames which are guaranteed (for now?) to contain the image data ID.

Closes #394

2021-09-06 16:46 UTC, ghisvail commented
This is the cleanest I could do given the state of the ADNI code.

2021-09-07 08:00 UTC, omar-rifai requested changes
This seems to work for anat but not for pet images

2021-09-07 08:08 UTC, ghisvail commented
Logs?

________________________________
De : omar-rifai ***@***.***>
Envoyé : mardi 7 septembre 2021 à 10:00
À : aramis-lab/clinica
Cc : VAILLANT Ghislain; Author
Objet : Re: [aramis-lab/clinica] Fix image path finder in ADNI converter (#411)


@omar-rifai requested changes on this pull request.

This seems to work for anat but not for pet images

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://fra01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Faramis-lab%2Fclinica%2Fpull%2F411%23pullrequestreview-747664410&data=04%7C01%7Cghislain.vaillant%40icm-institute.org%7Ce04c2dd5388441ade94808d971d5912c%7C9df7cf1718fa41508b00dc5e754777d8%7C0%7C0%7C637665984345056673%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=nxjle036ShIYwtxofSuuRJb0tW9Iavc3Uv9OycNhPIE%3D&reserved=0>, or unsubscribe<https://fra01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAO7U3462DMR2JKP32G3W4DUAXBB7ANCNFSM5DQZASLQ&data=04%7C01%7Cghislain.vaillant%40icm-institute.org%7Ce04c2dd5388441ade94808d971d5912c%7C9df7cf1718fa41508b00dc5e754777d8%7C0%7C0%7C637665984345066666%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=JCoETHXPWOnfhiyxHk3Qi5E4gXk2mPAC5w80tKYJ4Eg%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://fra01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cghislain.vaillant%40icm-institute.org%7Ce04c2dd5388441ade94808d971d5912c%7C9df7cf1718fa41508b00dc5e754777d8%7C0%7C0%7C637665984345066666%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=KS7vGqQ0D4A2gnSeNgX6yqcmgWkK5rpAAjhqpCvLbAc%3D&reserved=0> or Android<https://fra01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cghislain.vaillant%40icm-institute.org%7Ce04c2dd5388441ade94808d971d5912c%7C9df7cf1718fa41508b00dc5e754777d8%7C0%7C0%7C637665984345076667%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=KVAtpzewy92vCVMl0%2B9GvaWGTmhhBVBfMdoOkme4GHo%3D&reserved=0>.

2021-09-07 09:10 UTC, omar-rifai commented
Unfortunately I have no error logs. The data simply seems to be missing.

2021-09-07 09:54 UTC, omar-rifai approved these changes

2021-09-07 09:54 UTC, omar-rifai commented
Looks good, will merge.

2021-09-08 09:42 UTC, merged