Enable FreeSurfer to run with missing files
aramis-lab/clinica pull request #524
Opened 2021-12-09 09:36 UTC by MatthieuJoulot

Clinica's file reader current version doesn't allow to visualize missing files (*T1w.nii.gz) and to run the pipeline at the same time.
To enable this and give more flexibility, we return the error message containing the missing files and the results together. the message will be empty if no files are missing.

2021-12-09 10:30 UTC, ghisvail requested changes

2021-12-09 10:30 UTC, ghisvail commented on clinica/utils/inputs.py
> +    return results, error_message
There is a large potential for refactoring with the `raise_exception` case. Basically the error message construction code is the same, only what is done with it (raise in an exception or return the error message as a result) actually changes.

2021-12-09 10:30 UTC, ghisvail commented on clinica/utils/inputs.py
> +    return results, error_message
That would make the code clearer : one section building the error message, one section returning or raising based on the input arguments.

2021-12-13 13:04 UTC, omar-rifai commented on clinica/utils/inputs.py
> +    return results, error_message
An alternative to changing the return type (and hence updating all the calls to the function), is to add a new parameter variable (e.g `print_errors=False`) which prints the error messages if activated. I'm not saying we should go ahead with this solution, but maybe to keep in mind.

2021-12-14 10:32 UTC, omar-rifai commented
Currently if the first file of a tsv is missing, the pipeline seems to skip the file and execute the second subject with no warning message. I did not wait for it to finish execution but I was wondering whether that is the expected behavior?

2021-12-14 14:57 UTC, omar-rifai commented
@ghisvail , is all good with the required modification? If so we can merge.

2021-12-14 15:00 UTC, omar-rifai approved these changes

2021-12-14 15:25 UTC, ghisvail commented on clinica/pipelines/t1_freesurfer/t1_freesurfer_pipeline.py
> +        if error_message != "":
```suggestion
        if error_message:
```

2021-12-14 15:26 UTC, ghisvail commented on clinica/pipelines/t1_freesurfer/t1_freesurfer_pipeline.py
> +        if t1w_files == []:
```suggestion
        if not t1w_files:
```

2021-12-14 15:27 UTC, ghisvail requested changes
Have a look of the suggestions, the rest looks good to me 👍

2021-12-14 16:20 UTC, ghisvail approved these changes

2021-12-14 16:20 UTC, merged