Tighten the check on the session id values
aramis-lab/clinica pull request #544
Opened 2022-01-12 14:44 UTC by omar-rifai

Some unwanted `session_id` values were copied from ADNI's metadata. This fix tighten the check on the format of the `session_id`

2022-01-12 14:44 UTC, pep8speaks commented
Hello @omar-rifai! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`clinica/iotools/converters/adni_to_bids/adni_utils.py`](https://github.com/aramis-lab/clinica/blob/7b6fe631dd4a0384a524f21f3b4e235b6d1d4d7b/clinica/iotools/converters/adni_to_bids/adni_utils.py):

> [Line 723:6](https://github.com/aramis-lab/clinica/blob/7b6fe631dd4a0384a524f21f3b4e235b6d1d4d7b/clinica/iotools/converters/adni_to_bids/adni_utils.py#L723): [E901](https://duckduckgo.com/?q=pep8%20E901) IndentationError: unindent does not match any outer indentation level

2022-01-12 15:38 UTC, ghisvail requested changes
I like the proposed change to use an acceptance regex 👍

2022-01-12 15:38 UTC, ghisvail commented on clinica/iotools/converters/adni_to_bids/adni_utils.py
> +        df_subj_session.session_id.str.contains("ses-M\d*")
Change to 1 or more digit:

```suggestion
        df_subj_session.session_id.str.contains("ses-M\d+")
```

2022-01-13 15:21 UTC, omar-rifai commented on clinica/iotools/converters/adni_to_bids/adni_utils.py
> +        df_subj_session.session_id.str.contains("ses-M\d*")
commited

2022-01-13 16:02 UTC, merged