[REF] Refactor `get_suvr_mask`
aramis-lab/clinica pull request #749
Opened 2022-09-15 10:36 UTC by NicolasGensollen

Same as #748 but for function `get_suvr_mask`

2022-09-15 17:35 UTC, ghisvail commented
Fixed the conflicts while rebasing on `dev`

2022-09-16 07:29 UTC, NicolasGensollen commented
> Fixed the conflicts while rebasing on `dev`

Great! Thanks for taking care of that! 👍

2022-09-16 07:51 UTC, ghisvail requested changes
LGTM, with minor corrections

2022-09-16 07:51 UTC, ghisvail commented on test/unittests/utils/test_pet.py
> +    assert get_suvr_mask(label).exists()
"Unresolved attribute reference 'exists' for class 'PathLike'"

```suggestion
    assert Path(get_suvr_mask(label)).exists()
```

2022-09-16 07:51 UTC, ghisvail commented on clinica/utils/pet.py
> +    MASKS_DIR = CURRENT_DIR.parent.parent / "resources/masks"
"Variable in function should be lowercase"

2022-09-16 07:51 UTC, ghisvail commented on clinica/utils/pet.py
> +    MASKS_DIR = CURRENT_DIR.parent.parent / "resources/masks"
also:

```suggestion
    CURRENT_DIR = Path(os.path.realpath(__file__))
    MASKS_DIR = CURRENT_DIR.parent.parent / "resources" / "masks"
```

2022-09-16 08:16 UTC, ghisvail commented on clinica/utils/pet.py
> +    MASKS_DIR = CURRENT_DIR.parent.parent / "resources" / "masks"
```suggestion
    current_dir = Path(os.path.realpath(__file__))
    masks_dir = current_dir.parent.parent / "resources" / "masks"
```

2022-09-16 08:17 UTC, ghisvail commented on clinica/utils/pet.py
> +    return MASKS_DIR / suvr_reference_region_labels_to_filenames[suvr_reference_region]
```suggestion
    return masks_dir / suvr_reference_region_labels_to_filenames[suvr_reference_region]
```

2022-09-16 08:38 UTC, merged