[REF] Refactor and test `clinica.utils.inputs`
aramis-lab/clinica pull request #761
Opened 2022-10-03 14:58 UTC by NicolasGensollen

This PR proposes to refactor the utilities from `clinica/utils/inputs.py`:

- Add type hints
- Rewrite docstrings to make them NumpyDoc compliant
- Refactor some functions to make the code easier to read and maintain
- Add unit tests

I haven't tested `fetch_file` and `get_file_from_server` since their proper testing is a bit more involved and this PR is already quite large... I propose to work on this in a future PR.

2022-10-05 11:20 UTC, MatthieuJoulot approved these changes
LGTM

2022-10-05 14:29 UTC, ghisvail requested changes
Went through the usual type and spell checking

2022-10-05 14:29 UTC, ghisvail commented on clinica/utils/inputs.py
> +    from clinica.utils.stream import cprint
type alignement

```suggestion
def _list_subjects_sub_folders(
    root_dir: os.PathLike, groups_dir: os.PathLike
) -> List[os.PathLike]:
    from clinica.utils.stream import cprint
    from pathlib import Path

    root_dir = Path(root_dir)
    groups_dir = Path(groups_dir)
```

2022-10-05 14:29 UTC, ghisvail commented on clinica/utils/inputs.py
> +def _read_files_parrallel(
typo parrallel

2022-10-05 14:29 UTC, ghisvail commented on clinica/utils/inputs.py
> +    input_directory: str,
type alignment

```suggestion
    input_directory: os.PathLike,
```

2022-10-05 14:29 UTC, ghisvail commented on clinica/utils/inputs.py
> +    input_directory: str,
type alignment

```suggestion
    input_directory: os.PathLike,
```

2022-10-05 14:29 UTC, ghisvail commented on clinica/utils/inputs.py
> +    contain upper case letters that do not exists in the existing file path.
found by PyCharm's spell checker

```suggestion
    This function is case-insensitive, meaning that the pattern argument can, for example,
    contain upper case letters that do not exist in the existing file path.
```

2022-10-05 14:29 UTC, ghisvail commented on clinica/utils/inputs.py
> +        Path to cache. Defaul="~/.cache/clinica/data".
spell checking

```suggestion
        Path to cache. Default="~/.cache/clinica/data".
```

2022-10-05 14:29 UTC, ghisvail commented on test/unittests/utils/test_utils_inputs.py
> +    """
type alignment

```suggestion
    """
    from pathlib import Path
    
    directory = Path(directory)
```

2022-10-05 14:29 UTC, ghisvail commented on test/unittests/utils/test_utils_inputs.py
> +    """
type alignment
```suggestion
    """
    from pathlib import Path

    directory = Path(directory)
```

2022-10-05 14:29 UTC, ghisvail commented on test/unittests/utils/test_utils_inputs.py
> +        _common_checks(1, folder_type)
Expected type 'PathLike', got 'int' instead

2022-10-05 14:29 UTC, ghisvail commented on test/unittests/utils/test_utils_inputs.py
> +        _common_checks("fooooo", folder_type)
Expected type 'PathLike', got 'str' instead

2022-10-05 14:29 UTC, ghisvail commented on test/unittests/utils/test_utils_inputs.py
> +    errors = []
Local variable 'errors' value is not used

2022-10-05 14:29 UTC, ghisvail commented on test/unittests/utils/test_utils_inputs.py
> +    informations = [
Typo: In word 'informations'

PyCharm's spell checker suggests renaming to 'information'

2022-10-06 08:56 UTC, ghisvail commented on test/unittests/utils/test_utils_inputs.py
> +        _check_information(42)
Looks like this is still unresolved

2022-10-06 08:56 UTC, ghisvail commented on test/unittests/utils/test_utils_inputs.py
> +        _common_checks(1, folder_type)
Looks like this is still unresolved

2022-10-06 09:00 UTC, NicolasGensollen commented on test/unittests/utils/test_utils_inputs.py
> +        _check_information(42)
It's the purpose of this test to check that passing something else than a dict raises a TypeError...

2022-10-06 09:08 UTC, ghisvail commented on test/unittests/utils/test_utils_inputs.py
> +        _common_checks(1, folder_type)
Since the type mismatch is intentional:

```suggestion
        _common_checks(1, folder_type)  # noqa
```

2022-10-06 09:12 UTC, ghisvail approved these changes

2022-10-06 09:30 UTC, merged