[REF] Extract Step 2 of `DWIPreprocessingUsingPhasediff` into its own workflow
aramis-lab/clinica pull request #897
Opened 2023-03-27 07:52 UTC by NicolasGensollen

This is still WIP.

Similar to #893 for Step 1, this PR proposes to extract the Step 2 of the DWIPreprocessingUsingPhaseDiff pipeline into its own workflow. Also adds functional test for the extracted workflow in isolation.

2023-03-29 09:39 UTC, NicolasGensollen commented
The Jenkins failure is expected as the data needed for the tests aren't merged and uploaded yet.

2023-04-03 09:51 UTC, MatthieuJoulot requested changes
Looks good. Just one small suggestion.
I'll test it asap with the data you've generated.

2023-04-03 09:51 UTC, MatthieuJoulot commented on clinica/pipelines/dwi_preprocessing_using_fmap/dwi_preprocessing_using_phasediff_fmap_workflows.py
> +    Calibrate and register the field map.
```suggestion
    Calibrates and registers the field map.
```

2023-04-04 12:46 UTC, MatthieuJoulot requested changes

2023-04-04 12:46 UTC, MatthieuJoulot commented on test/nonregression/pipelines/test_run_pipelines_dwi.py
> +        assert similarity_measure(out_file, ref_file, 0.99)
```suggestion
        assert similarity_measure(out_file, ref_file, 0.98)
```
That way we account for the difference in precision between linux and mac. 0.99 doesn't get through mac

2023-04-04 12:46 UTC, NicolasGensollen commented
Tests are passing with the updated data.
Let me know if you think there are still things to change before we merge @MatthieuJoulot !

2023-04-04 13:32 UTC, NicolasGensollen commented
Thanks for the reviews @MatthieuJoulot !
Merging...

2023-04-04 13:32 UTC, merged